### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by londere** [MathieuRita/MVA_Remote#4]
Hello My name is Agustin and I would like to replicate the obtained results posted in your code. However in the jupyter notebook states the need of the FFDNet_data.zip, is any way that you can share the mentioned file or tell me if i need to request it somewhere else.

In advance thanks.

**Comment by MathieuRita** [comment]
Hi Augustin! This project was carried out during my Masters a few years ago.  I was asked to remove the data because it is the property of the university. In case of any academic interest, you can contact Emanuele Dalsasso who was the TA of the course at that time (https://scholar.google.com/citations?user=4bfkX98AAAAJ&hl=it)

**Comment by londere** [comment]
Thanks a lot for the insight Mathieu, I'll contact PhD. Dalsasso.
